# Generated by Django 2.2 on 2022-05-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_db_global_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project',
            name='user_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
