# Generated by Django 2.2 on 2022-05-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_db_project_encryption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_project',
            old_name='encryption',
            new_name='encryption_input',
        ),
        migrations.AddField(
            model_name='db_project',
            name='encryption_insert',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
