# Generated by Django 2.2 on 2022-05-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_db_project_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_apis',
            name='cert',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='db_apis_log',
            name='cert',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='db_login',
            name='cert',
            field=models.CharField(default='no', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='db_step',
            name='cert',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
