# Generated by Django 2.2 on 2022-05-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_auto_20220506_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_cases',
            name='concurrent',
            field=models.BooleanField(default=True),
        ),
    ]
